apps/exports/urls.py
from django.urls import path
from . import views


app_name = 'exports'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'create/', views.create_export_config, name='create_export_config'),
    path(r'create/multi-project/', views.create_multi_export_config, name='create_multi_export_config'),
    path(r'view/<int:export_id>/', views.export_details, name='export_details'),
    path(r'view/<int:export_id>/edit/', views.edit_export_config, name='edit_export_config'),
    path(r'view/<int:export_id>/delete/', views.delete_export_config, name='delete_export_config'),
    path(r'download/<int:export_id>/config-file/', views.download_export_file, name='download_export_file'),
    path(r'download/version/<int:version_id>/config-file/', views.download_export_file_version,
         name='download_export_file_version'),
    path(r'view/multi-project/<int:export_id>/', views.multi_export_details, name='multi_export_details'),
    path(r'view/multi-project/<int:export_id>/run/<int:run_id>/', views.multi_export_run_details,
         name='multi_export_run_details'),
    path(r'view/multi-project/<int:export_id>/edit/', views.edit_multi_export_config,
         name='edit_multi_export_config'),
    path(r'view/multi-project/<int:export_id>/delete/', views.delete_multi_export_config,
         name='delete_multi_export_config'),
    path(r'download/multi-project/<int:export_id>/config-file/', views.download_multi_export_file,
         name='download_multi_export_file'),
    path(r'api/run/<int:export_id>/', views.run_export, name='run_export'),
    path(r'api/run/multi-project/<int:export_id>/', views.run_multi_export, name='run_multi_export'),
    path(r'databases/', views.databases, name='databases'),
    path(r'databases/create/', views.create_database, name='create_database'),
    path(r'databases/<int:database_id>/edit/', views.edit_database, name='edit_database'),
]

commcare_sync/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view


schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('commcare/', include('apps.commcare.urls')),
    path('exports/', include('apps.exports.urls')),
    path('users/', include('apps.users.urls')),

    path('', include('apps.web.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
]

apps/exports/forms.py
from django import forms

from apps.commcare.models import CommCareProject, CommCareAccount
from .models import ExportConfig, MultiProjectExportConfig, ExportDatabase


class ExportConfigForm(forms.ModelForm):
    project = forms.ModelChoiceField(CommCareProject.objects.order_by('domain'))
    account = forms.ModelChoiceField(CommCareAccount.objects.order_by('username'))
    database = forms.ModelChoiceField(ExportDatabase.objects.order_by('name'))
    extra_args = forms.CharField(widget=forms.TextInput, required=False)

    class Meta:
        model = ExportConfig
        fields = ('name', 'project', 'account', 'database', 'is_paused', 'time_between_runs',
                  'config_file', 'batch_size', 'extra_args')


class MultiProjectExportConfigForm(forms.ModelForm):

    class Meta:
        model = MultiProjectExportConfig
        fields = ('name', 'projects', 'account', 'database', 'is_paused', 'time_between_runs',
                  'config_file', 'batch_size', 'extra_args')

    projects = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={"class": "checkbox"}),
        queryset=CommCareProject.objects.order_by('domain'),
    )


class CreateExportDatabaseForm(forms.ModelForm):

    class Meta:
        model = ExportDatabase
        fields = ('name', 'connection_string')


class EditExportDatabaseForm(forms.ModelForm):

    class Meta:
        model = ExportDatabase
        fields = ('name',)

apps/exports/views.py
import json
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_POST
from reversion.models import Version

from .forms import ExportConfigForm, MultiProjectExportConfigForm, EditExportDatabaseForm, CreateExportDatabaseForm
from .models import ExportConfig, MultiProjectExportConfig, ExportDatabase, ExportRun, MultiProjectExportRun
from .tasks import run_export_task, run_multi_project_export_task


@login_required
def home(request):
    exports = ExportConfig.objects.order_by('-updated_at')
    multi_project_exports = MultiProjectExportConfig.objects.order_by('-updated_at')

    return render(request, 'exports/exports_home.html', {
        'active_tab': 'exports',
        'exports': exports,
        'multi_project_exports': multi_project_exports,
    })


@login_required
def create_export_config(request):

    if request.method == 'POST':
        form = ExportConfigForm(request.POST, request.FILES)
        if form.is_valid():
            export = form.save(commit=False)
            export.created_by = request.user
            export.save()
            messages.success(request, f'Export "{export.name}" was successfully created.')
            return HttpResponseRedirect(reverse('exports:export_details', args=[export.id]))
    else:
        form = ExportConfigForm()

    return render(request, 'exports/create_export.html', {
        'active_tab': 'create_export',
        'form': form,
    })


@login_required
def create_multi_export_config(request):
    if request.method == 'POST':
        form = MultiProjectExportConfigForm(request.POST, request.FILES)
        if form.is_valid():
            export = form.save(commit=False)
            export.created_by = request.user
            export.save()
            form.save_m2m()
            messages.success(request, f'Export {export.name} was successfully created.')
            return HttpResponseRedirect(reverse('exports:multi_export_details', args=[export.id]))
    else:
        form = MultiProjectExportConfigForm()

    return render(request, 'exports/create_multi_project_export.html', {
        'active_tab': 'create_multi_export',
        'form': form,
    })


@login_required
def edit_export_config(request, export_id):
    export = get_object_or_404(ExportConfig, id=export_id)
    if request.method == 'POST':
        form = ExportConfigForm(request.POST, request.FILES, instance=export)
        if form.is_valid():
            export = form.save()
            messages.success(request, f'Export {export.name} was successfully saved.')
            return HttpResponseRedirect(reverse('exports:export_details', args=[export.id]))
    else:
        form = ExportConfigForm(instance=export)

    return render(request, 'exports/edit_export.html', {
        'active_tab': 'exports',
        'form': form,
        'export': export,
    })


@login_required
def edit_multi_export_config(request, export_id):
    export = get_object_or_404(MultiProjectExportConfig, id=export_id)
    if request.method == 'POST':
        form = MultiProjectExportConfigForm(request.POST, request.FILES, instance=export)
        if form.is_valid():
            export = form.save()
            messages.success(request, f'Export {export.name} was successfully created.')
            return HttpResponseRedirect(reverse('exports:multi_export_details', args=[export.id]))
    else:
        form = MultiProjectExportConfigForm(instance=export)

    return render(request, 'exports/edit_multi_project_export.html', {
        'active_tab': 'create_multi_export',
        'form': form,
    })


@login_required
def delete_export_config(request, export_id):
    export = get_object_or_404(ExportConfig, id=export_id)
    if request.method == 'POST':
        export.delete()
        messages.success(request, f'Export file "{export.name}" was successfully deleted.')
        return HttpResponseRedirect(reverse('exports:home'))
    return render(request, 'exports/delete_export.html', {
        'active_tab': 'exports',
        'export': export,
    })


@login_required
def delete_multi_export_config(request, export_id):
    export = get_object_or_404(MultiProjectExportConfig, id=export_id)
    if request.method == 'POST':
        export.delete()
        messages.success(request, f'Export file "{export.name}" was successfully deleted.')
        return HttpResponseRedirect(reverse('exports:home'))
    return render(request, 'exports/delete_export.html', {
        'active_tab': 'exports',
        'export': export,
    })


@login_required
def export_details(request, export_id):
    export = get_object_or_404(ExportConfig, id=export_id)
    runs = export.runs
    hide_skipped = _get_hide_skipped_from_request(request)
    if hide_skipped:
        runs = runs.exclude(status__in=[ExportRun.SKIPPED, ExportRun.QUEUED])

    return render(request, 'exports/export_details.html', {
        'active_tab': 'exports',
        'export': export,
        'runs': runs.order_by('-created_at')[:_get_ui_page_size(request)],
        'hide_skipped': hide_skipped,
    })


@login_required
def download_export_file(request, export_id):
    export = get_object_or_404(ExportConfig, id=export_id)
    return _download_config_file(export.config_file)


@login_required
def download_multi_export_file(request, export_id):
    export = get_object_or_404(MultiProjectExportConfig, id=export_id)
    return _download_config_file(export.config_file)


@login_required
def download_export_file_version(request, version_id):
    version = get_object_or_404(Version, id=version_id)
    return _download_config_file(version.field_dict['config_file'])


def _download_config_file(export_file_field):
    response = HttpResponse(export_file_field.read(), content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename={os.path.basename(export_file_field.name)}'
    return response


@login_required
def multi_export_details(request, export_id):
    export = get_object_or_404(MultiProjectExportConfig, id=export_id)
    runs = export.runs
    hide_skipped = _get_hide_skipped_from_request(request)
    if hide_skipped:
        runs = runs.exclude(status__in=[ExportRun.SKIPPED, ExportRun.QUEUED])

    return render(request, 'exports/multi_project_export_details.html', {
        'active_tab': 'exports',
        'export': export,
        'runs': runs.order_by('-created_at')[:_get_ui_page_size(request)],
        'hide_skipped': hide_skipped,

    })


@login_required
def multi_export_run_details(request, export_id, run_id):
    export_run = get_object_or_404(MultiProjectExportRun, id=run_id)
    if export_run.base_export_config.id != export_id:
        raise Http404(f'Export id {export_id} did not match run value of {export_run.base_export_config.id }!')
    return render(request, 'exports/multi_project_export_run_details.html', {
        'active_tab': 'exports',
        'export_run': export_run,
        'export': export_run.base_export_config,
        'runs': export_run.partial_runs.order_by('-created_at')[:_get_ui_page_size(request)],
    })


@login_required
@require_POST
def run_export(request, export_id):
    export = get_object_or_404(ExportConfig, id=export_id)

    options = json.loads(request.body)
    force_sync = options.get('forceSync', False)
    export_record = ExportRun.objects.create(
        base_export_config=export,
        export_config_version=export.latest_version,
        triggered_from_ui=True,
        triggering_user=request.user,
    )

    result = run_export_task.delay(export_record.id, force_sync_all_data=force_sync, ignore_schedule_checks=True)
    return HttpResponse(result.task_id)


@login_required
@require_POST
def run_multi_export(request, export_id):
    export = get_object_or_404(MultiProjectExportConfig, id=export_id)

    options = json.loads(request.body)
    force_sync = options.get('forceSync', False)
    export_record = MultiProjectExportRun.objects.create(
        base_export_config=export,
        export_config_version=export.latest_version,
        triggered_from_ui=True,
        triggering_user=request.user
    )

    result = run_multi_project_export_task.delay(
        export_record.id, force_sync_all_data=force_sync, ignore_schedule_checks=True,
    )
    return HttpResponse(result.task_id)


@login_required
def databases(request):
    databases = ExportDatabase.objects.order_by('name')
    return render(request, 'exports/databases.html', {
        'active_tab': 'databases',
        'databases': databases,
    })


@user_passes_test(lambda u: u.is_superuser, login_url='/admin-required')
def create_database(request):
    if request.method == 'POST':
        form = CreateExportDatabaseForm(request.POST, request.FILES)
        if form.is_valid():
            db = form.save(commit=False)
            db.owner = request.user
            db.save()
            messages.success(request, f'Database {db.name} was successfully created.')
            return HttpResponseRedirect(reverse('exports:databases'))
    else:
        form = CreateExportDatabaseForm()

    return render(request, 'exports/create_database.html', {
        'active_tab': 'create_export',
        'form': form,
    })


@user_passes_test(lambda u: u.is_superuser)
def edit_database(request, database_id):
    db = get_object_or_404(ExportDatabase, id=database_id)
    if request.method == 'POST':
        form = EditExportDatabaseForm(request.POST, instance=db)
        if form.is_valid():
            db = form.save()
            messages.success(request, f'Database "{db.name}" was successfully updated.')
            return HttpResponseRedirect(reverse('exports:databases'))
    else:
        form = EditExportDatabaseForm(instance=db)

templates/exports/create_database.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Create Database</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="field">
      <label class="label">Name</label>
      <div class="control">
        {{ form.name }}
      </div>
      {{ form.name.errors }}
    </div>
    <div class="field">
      <label class="label">Connection String</label>
      <div class="control">
        {{ form.connection_string }}
      </div>
      {{ form.connection_string.errors }}
    </div>
    <div class="field is-grouped">
        <div class="control">
            <input class="button is-primary" type="submit" value="Create">
        </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/exports/create_export.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Create Export Configuration</h1>
  <form method="post" enctype="multipart/form-data">
    {% include 'exports/partials/export_form.html' %}
    <div class="field is-grouped">
        <div class="control">
            <input class="button is-primary" type="submit" value="Create">
        </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/exports/create_multi_project_export.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Create Export Configuration</h1>
  <form method="post" enctype="multipart/form-data">
    {% include 'exports/partials/multi_project_export_form.html' %}
    <div class="field is-grouped">
        <div class="control">
            <input class="button is-primary" type="submit" value="Create">
        </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/exports/databases.html
{% extends "web/app/app_base.html" %}
{% block app %}
{% load exports_tags %}
{% load humanize %}
<section class="section app-card">
  <h1 class="title">Database Connections</h1>
  <h2 class="subtitle">Manage the databases that you export data to here</h2>
{% if databases.exists %}
  <p class="notification is-info is-light">
    Note: this app will not create new databases for you. Any connections you add must point to valid, existing databases.
  </p>
  {% if user.is_superuser %}
  <a class="button is-primary is-rounded is-small is-outlined" href="{% url 'exports:create_database' %}">
    <span class="icon">
      <i class="fa fa-plus"></i>
    </span>
    <span>New Database Connection</span>
  </a>
  {% endif %}
  <table class="table is-striped is-fullwidth">
    <thead>
    <tr>
      <th>Database</th>
      <th>Owner</th>
    </tr>
    </thead>
    <tbody>
    {% for database in databases %}
      <tr>
        <td>
          {% if user.is_superuser %}
          <a href="{% url 'exports:edit_database' database.id %}">
            {{ database.name }}
          </a>
          {% else %}
          {{ database.name }}
          {% endif %}
        </td>
        <td>{% if request.user == database.owner %}You{% else %}{{ database.owner.get_display_name }}{% endif %}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <section class="notification is-warning is-light">
    No database connections found!
  </section>
  <a class="button is-primary " href="{% url 'exports:create_database' %}">
    <span class="icon">
      <i class="fa fa-plus"></i>
    </span>
    <span>Add Your First Database Connection</span>
  </a>
{% endif  %}
</section>
{% endblock app %}

templates/exports/delete_export.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Delete {{ export.name }}?</h1>
  <h2 class="subtitle">Are you sure you want to delete this export? This operation is not reversible.</h2>
  <div class="content">
    <p>After deleting, the following items will be deleted and the export will stop syncing data.</p>
    <ul>
      <li>The Export and its configuration file.</li>
      <li>All {{ export.runs.count }} records of the export's individual runs and associated logs.</li>
    </ul>
    <p><strong>Note: the underlying data associated with the export must be deleted separately.</strong></p>
  </div>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field is-grouped">
      <div class="control">
        <input class="button is-danger" type="submit" value="Delete Export">
      </div>
      <div class="control">
        <a class="button is-primary is-outlined" href="{{ export.details_url }}">Cancel</a>
      </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/exports/edit_database.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Edit Database</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="field">
      <label class="label">Name</label>
      <div class="control">
        {{ form.name }}
      </div>
      {{ form.name.errors }}
    </div>
    <div class="field is-grouped">
        <div class="control">
            <input class="button is-primary" type="submit" value="Save">
        </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/exports/edit_export.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Edit {{ export.name }}</h1>
  <form method="post" enctype="multipart/form-data">
    {% include 'exports/partials/export_form.html' %}
    <div class="field is-grouped">
      <div class="control">
        <input class="button is-primary" type="submit" value="Save">
      </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/exports/edit_multi_project_export.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Edit {{ export.name }}</h1>
  <form method="post" enctype="multipart/form-data">
    {% include 'exports/partials/multi_project_export_form.html' %}
    <div class="field is-grouped">
      <div class="control">
        <input class="button is-primary" type="submit" value="Save">
      </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/exports/export_details.html
{% extends "web/app/app_base.html" %}
{% load humanize %}
{% load static %}
{% load dateformat_tags %}
{% block app %}
<section class="section app-card">
  <div class="level">
    <!-- Left side -->
    <div class="level-left">
      <h1 class="title">{{ export.name }} - Details</h1>
    </div>
    <div class="level-right">
      <div class="buttons">
      <a class="button is-danger is-rounded is-small is-outlined" href="{% url 'exports:delete_export_config' export.id %}">
        <span class="icon">
          <i class="fa fa-times"></i>
        </span>
        <span>Delete</span>
      </a>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <span class="heading">Project Space</span>
      <h2>
        <a href="{{ export.project.url }}" target="_blank">{{ export.project.domain }}
          <i class="fa fa-external-link"></i>
        </a>
      </h2>
    </div>
    <div class="column">
      <span class="heading">Account</span>
      <h2>
        {{ export.account.username }}
      </h2>
    </div>
    <div class="column">
      <span class="heading">Database</span>
      <h2>
        {{ export.database.name }}
      </h2>
    </div>
    <div class="column">
      <span class="heading">Created By</span>
      <h2>
        {% if request.user == export.created_by %}You{% else %}{{ export.created_by.username}}{% endif %}
      </h2>
    </div>
    <div class="column">
      <span class="heading">Last Modified</span>
      <h2>
        {{ export.updated_at|naturaltime }}
      </h2>
    </div>
  </div>
  <div class="buttons">
    <a class="button is-primary is-rounded is-small" href="{% url 'exports:download_export_file' export.id %}">
      <span class="icon">
        <i class="fa fa-download"></i>
      </span>
      <span>Download Config File</span>
    </a>
    <a class="button is-primary is-rounded is-small is-outlined" href="{% url 'exports:edit_export_config' export.id %}">
        <span class="icon">
          <i class="fa fa-edit"></i>
        </span>
        <span>Edit</span>
      </a>
  </div>
</section>
{% include 'exports/partials/run_history.html' %}
{% endblock app %}
{% block page_js %}
<script src="{% static 'celery_progress/celery_progress.js' %}"></script>
<script src="{% static 'js/app-bundle.js' %}"></script>
<script>
    const apiUrl = "{% url 'exports:run_export' export.id %}";
    const progressUrl = "{% url 'celery_progress:task_status' 'task-id-stub' %}";
    const Exports = SiteJS.app.Exports;
    document.addEventListener("DOMContentLoaded", function () {
      Exports.initializeExportRunButton(apiUrl, progressUrl);
    });
    document.addEventListener('DOMContentLoaded', Exports.setupLogTriggers);
</script>
{% endblock page_js %}

templates/exports/exports_home.html
{% extends "web/app/app_base.html" %}
{% block app %}
{% load exports_tags %}
{% load humanize %}
<section class="section app-card">
  <h1 class="title">Export Configurations</h1>
{% if exports.exists %}
  <a class="button is-primary is-rounded is-small is-outlined" href="{% url 'exports:create_export_config' %}">
    <span class="icon">
      <i class="fa fa-plus"></i>
    </span>
    <span>New Export</span>
  </a>
  <table class="table is-striped is-fullwidth">
    <thead>
    <tr>
      <th>Export</th>
      <th>Project</th>
      <th>Created By</th>
      <th>Last Run</th>
    </tr>
    </thead>
    <tbody>
    {% for export in exports %}
      <tr>
        <td>
          <a href="{% url 'exports:export_details' export.id %}">{{ export.name }}</a>
          {% if export.is_paused %}
            <i title="This export is paused." class="fa fa-pause-circle has-text-grey-light"></i>
          {% endif %}
        </td>
        <td>{{ export.project.domain }}</td>
        <td>{% if request.user == export.created_by %}You{% else %}{{ export.created_by.get_display_name }}{% endif %}</td>
        <td>{{ export.last_run.status|to_status_icon }} {{ export.last_run.created_at|naturaltime }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <section class="notification is-warning is-light">
    No export configurations found!
  </section>
  <a class="button is-primary " href="{% url 'exports:create_export_config' %}">
    <span class="icon">
      <i class="fa fa-plus"></i>
    </span>
    <span>Add Your First Export</span>
  </a>
{% endif  %}
</section>
{% if multi_project_exports.exists %}
<section class="section app-card">
  <h1 class="title">Multi-Project Export Configurations</h1>
  <a class="button is-primary is-rounded is-small is-outlined" href="{% url 'exports:create_multi_export_config' %}">
    <span class="icon">
      <i class="fa fa-plus"></i>
    </span>
    <span>New Multi-Project Export</span>
  </a>
  <table class="table is-striped is-fullwidth">
    <thead>
    <tr>
      <th>Export</th>
      <th>Projects</th>
      <th>Created By</th>
      <th>Last Run</th>
    </tr>
    </thead>
    <tbody>
    {% for export in multi_project_exports %}
      <tr>
        <td>
          <a href="{% url 'exports:multi_export_details' export.id %}">{{ export.name }}</a>
          {% if export.is_paused %}
            <i title="paused" class="fa fa-pause-circle"></i>
          {% endif %}
        </td>
        <td>{{ export.get_projects_display_short }}</td>
        <td>{% if request.user == export.created_by %}You{% else %}{{ export.created_by.get_display_name }}{% endif %}</td>
        <td>{{ export.last_run.status|to_status_icon }} {{ export.last_run.created_at|naturaltime }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</section>
{% endif %}
{% endblock app %}

templates/exports/multi_project_export_details.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% block app %}
{% include 'exports/partials/multi_export_details.html' %}
{% with True as is_multi_project %}
  {% include 'exports/partials/run_history.html' %}
{% endwith %}
{% endblock app %}
{% block page_js %}
<script src="{% static 'celery_progress/celery_progress.js' %}"></script>
<script src="{% static 'js/app-bundle.js' %}"></script>
<script>
    const apiUrl = "{% url 'exports:run_multi_export' export.id %}";
    const progressUrl = "{% url 'celery_progress:task_status' 'task-id-stub' %}";
    const Exports = SiteJS.app.Exports;
    document.addEventListener("DOMContentLoaded", function () {
      Exports.initializeExportRunButton(apiUrl, progressUrl);
    });
    document.addEventListener('DOMContentLoaded', Exports.setupLogTriggers);
</script>
{% endblock page_js %}

templates/exports/multi_project_export_run_details.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% load dateformat_tags %}
{% load exports_tags %}
{% block app %}
{% with True as show_back_button %}
{% include 'exports/partials/multi_export_details.html' %}
{% endwith %}
<section class="section app-card">
  <h1 class="title">Run Details</h1>
  <div class="columns">
    <div class="column">
      <span class="heading">Queued</span>
      <p>{{ export_run.created_at }}</p>
    </div>
    <div class="column">
      <span class="heading">Started</span>
      <p>{{ export_run.started_at|default:"---" }}</p>
    </div>
    <div class="column">
      <span class="heading">Duration</span>
      <p>{{ export_run.duration|readable_timedelta }}</p>
    </div>
    <div class="column">
      <span class="heading">Status</span>
      <p>{{ export_run.status|to_status_icon }} {{ export_run.status }}</p>
    </div>
  </div>
</section>
<section class="section app-card">
  <h1 class="title">Project-Level Runs</h1>
{% with True as is_partial_list %}
  {% include 'exports/partials/run_history_table.html' %}
{% endwith %}
{% endblock app %}
{% block page_js %}
<script src="{% static 'js/app-bundle.js' %}"></script>
<script>
  document.addEventListener('DOMContentLoaded', SiteJS.app.Exports.setupLogTriggers);
</script>
{% endblock %}