apps/exports/urls.py
from django.urls import path
from . import views


app_name = 'exports'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'create/', views.create_export_config, name='create_export_config'),
    path(r'create/multi-project/', views.create_multi_export_config, name='create_multi_export_config'),
    path(r'view/<int:export_id>/', views.export_details, name='export_details'),
    path(r'view/<int:export_id>/edit/', views.edit_export_config, name='edit_export_config'),
    path(r'view/<int:export_id>/delete/', views.delete_export_config, name='delete_export_config'),
    path(r'download/<int:export_id>/config-file/', views.download_export_file, name='download_export_file'),
    path(r'download/version/<int:version_id>/config-file/', views.download_export_file_version,
         name='download_export_file_version'),
    path(r'view/multi-project/<int:export_id>/', views.multi_export_details, name='multi_export_details'),
    path(r'view/multi-project/<int:export_id>/run/<int:run_id>/', views.multi_export_run_details,
         name='multi_export_run_details'),
    path(r'view/multi-project/<int:export_id>/edit/', views.edit_multi_export_config,
         name='edit_multi_export_config'),
    path(r'view/multi-project/<int:export_id>/delete/', views.delete_multi_export_config,
         name='delete_multi_export_config'),
    path(r'download/multi-project/<int:export_id>/config-file/', views.download_multi_export_file,
         name='download_multi_export_file'),
    path(r'api/run/<int:export_id>/', views.run_export, name='run_export'),
    path(r'api/run/multi-project/<int:export_id>/', views.run_multi_export, name='run_multi_export'),
    path(r'databases/', views.databases, name='databases'),
    path(r'databases/create/', views.create_database, name='create_database'),
    path(r'databases/<int:database_id>/edit/', views.edit_database, name='edit_database'),
]

commcare_sync/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view


schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('commcare/', include('apps.commcare.urls')),
    path('exports/', include('apps.exports.urls')),
    path('users/', include('apps.users.urls')),

    path('', include('apps.web.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
]

apps/exports/models.py
import reversion
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from reversion.models import Version

from apps.commcare.models import BaseModel
from apps.exports.scheduling import export_is_scheduled_to_run
from apps.exports.templatetags.dateformat_tags import readable_timedelta


class ExportDatabase(BaseModel):
    name = models.CharField(max_length=100)
    connection_string = models.CharField(max_length=500)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ExportConfigBase(BaseModel):
    name = models.CharField(max_length=100)
    account = models.ForeignKey('commcare.CommCareAccount', on_delete=models.CASCADE)
    database = models.ForeignKey(ExportDatabase, on_delete=models.CASCADE)
    config_file = models.FileField(upload_to='export-configs/')
    batch_size = models.PositiveIntegerField(
        default=500,
        help_text='How many cases to fetch at a time from CommCare. '
                  'Try increasing this number if your export gets stuck.',
    )
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_between_runs = models.PositiveIntegerField(
        default=int(settings.COMMCARE_SYNC_EXPORT_PERIODICITY / 60),
        help_text='How regularly to sync this export, in minutes.',
    )
    is_paused = models.BooleanField(default=False,
                                    help_text='Pausing an export will disable automatic syncing. '
                                              'You can still manually run it.')
    extra_args = models.TextField(blank=True)

    class Meta:
        abstract = True

    @property
    def last_run(self):
        runs = self.runs.exclude(status=ExportRun.QUEUED)
        return runs.order_by('-created_at')[0] if runs.exists() else None

    def is_scheduled_to_run(self):
        return export_is_scheduled_to_run(self, self.last_run)

    def has_queued_runs(self):
        if self.runs.exists():
            # Each run will ingest all new data when it is available, so we only need one run at a time.
            # We can therefore ignore all but the latest queued run.
            return self.runs.order_by('-created_at')[0].status == ExportRun.QUEUED
        return False

    def should_create_export_run(self):
        """If a new export_run should be created and celery task spawned
        """
        return self.is_scheduled_to_run() and not self.has_queued_runs()

    @property
    def latest_version(self):
        return Version.objects.get_for_object(self).first()

    @property
    def details_url(self):
        if isinstance(self, ExportConfig):
            return reverse('exports:export_details', args=[self.id])
        elif isinstance(self, MultiProjectExportConfig):
            return reverse('exports:multi_export_details', args=[self.id])
        else:
            raise ValueError(f"Can't find details URL for {self}")

    def save(self, **kwargs):
        with reversion.create_revision():
            super().save(**kwargs)


@reversion.register()
class ExportConfig(ExportConfigBase):
    project = models.ForeignKey('commcare.CommCareProject', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.project}'


@reversion.register()
class MultiProjectExportConfig(ExportConfigBase):
    projects = models.ManyToManyField('commcare.CommCareProject')

    def __str__(self):
        return f'{self.name} - {self.projects.count()} projects'

    def get_last_run_for_project(self, project):
        try:
            return MultiProjectPartialExportRun.objects.filter(
                parent_run__base_export_config=self,
                project=project
            ).order_by('-created_at')[0]
        except IndexError:
            return None

    def get_projects_display_short(self):
        project_count = self.projects.count()
        if project_count > 2:
            return mark_safe(f'{self.projects.all()[0].domain}<br>+ {project_count - 1} more')
        else:
            return mark_safe('<br>'.join(p.domain for p in self.projects.all()))


class ExportRunBase(BaseModel):
    QUEUED = 'queued'
    STARTED = 'started'
    MULTIPLE = 'multiple'
    COMPLETED = 'completed'
    FAILED = 'failed'
    SKIPPED = 'skipped'
    STATUS_CHOICES = (
        (QUEUED, 'queued'),
        (STARTED, 'started'),
        (COMPLETED, 'completed'),
        (FAILED, 'failed'),
        (MULTIPLE, 'multiple statuses'),  # MultiExport only
        (SKIPPED, 'skipped'),
    )
    started_at = models.DateTimeField(null=True, blank=True, help_text="When the export actually started running. "
                                                                       "It may have been created/queued earlier.")
    completed_at = models.DateTimeField(null=True, blank=True)
    triggered_from_ui = models.BooleanField(null=True, default=None)
    triggering_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,
                                        on_delete=models.SET_NULL)
    status = models.CharField(max_length=10, default=QUEUED, choices=STATUS_CHOICES)
    log = models.TextField(null=True, blank=True)

    class Meta:
        abstract = True

    def __str__(self):
        return f'{self.base_export_config.name} ({self.created_at})'

    @property
    def duration(self):
        if self.completed_at and self.started_at:
            return self.completed_at - self.started_at
        else:
            return None

    def get_duration_display(self):
        return readable_timedelta(self.duration)

    def mark_skipped(self):
        if not self.status == ExportRun.QUEUED:
            raise Exception("Can't mark a run that has been started skipped!")
        self.status = ExportRun.SKIPPED
        self.completed_at = timezone.now()
        self.save()


class ExportRun(ExportRunBase):
    base_export_config = models.ForeignKey(ExportConfig, on_delete=models.CASCADE, related_name='runs')
    export_config_version = models.ForeignKey(Version, on_delete=models.CASCADE, null=True)


class MultiProjectExportRun(ExportRunBase):
    base_export_config = models.ForeignKey(MultiProjectExportConfig, on_delete=models.CASCADE, related_name='runs')
    export_config_version = models.ForeignKey(Version, on_delete=models.CASCADE, null=True)


class MultiProjectPartialExportRun(ExportRunBase):
    parent_run = models.ForeignKey(MultiProjectExportRun, null=True, blank=True, on_delete=models.CASCADE,
                                   related_name='partial_runs')
    project = models.ForeignKey('commcare.CommCareProject', on_delete=models.CASCADE)

apps/exports/forms.py
from django import forms

from apps.commcare.models import CommCareProject, CommCareAccount
from .models import ExportConfig, MultiProjectExportConfig, ExportDatabase


class ExportConfigForm(forms.ModelForm):
    project = forms.ModelChoiceField(CommCareProject.objects.order_by('domain'))
    account = forms.ModelChoiceField(CommCareAccount.objects.order_by('username'))
    database = forms.ModelChoiceField(ExportDatabase.objects.order_by('name'))
    extra_args = forms.CharField(widget=forms.TextInput, required=False)

    class Meta:
        model = ExportConfig
        fields = ('name', 'project', 'account', 'database', 'is_paused', 'time_between_runs',
                  'config_file', 'batch_size', 'extra_args')


class MultiProjectExportConfigForm(forms.ModelForm):

    class Meta:
        model = MultiProjectExportConfig
        fields = ('name', 'projects', 'account', 'database', 'is_paused', 'time_between_runs',
                  'config_file', 'batch_size', 'extra_args')

    projects = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={"class": "checkbox"}),
        queryset=CommCareProject.objects.order_by('domain'),
    )


class CreateExportDatabaseForm(forms.ModelForm):

    class Meta:
        model = ExportDatabase
        fields = ('name', 'connection_string')


class EditExportDatabaseForm(forms.ModelForm):

    class Meta:
        model = ExportDatabase
        fields = ('name',)

templates/exports/partials/export_form.html
{% csrf_token %}
{{ form.non_field_errors }}
<div class="field">
  <label class="label">Name</label>
  <div class="control">
    {{ form.name }}
  </div>
  {{ form.name.errors }}
</div>
<div class="field">
  <label class="label">Project</label>
  <div class="select">
    {{ form.project }}
  </div>
  {{ form.project.errors }}
</div>
{% include 'exports/partials/export_form_shared.html' %}

templates/exports/partials/export_form_shared.html
<div class="field">
  <label class="label">Account</label>
  <div class="select">
    {{ form.account }}
  </div>
  {{ form.account.errors }}
</div>
<div class="field">
  <label class="label">Database</label>
  <div class="select">
    {{ form.database }}
  </div>
  {{ form.database.errors }}
</div>
<div class="field">
  <label class="label">Is Paused?</label>
  <div class="control">
    {{ form.is_paused }}
  </div>
  <p class="help">{{ form.is_paused.help_text }}</p>
  {{ form.is_paused.errors }}
</div>
<div class="field">
  <label class="label">Time Between Runs</label>
  <div class="control">
    {{ form.time_between_runs }}
  </div>
  <p class="help">{{ form.time_between_runs.help_text }}</p>
  {{ form.time_between_runs.errors }}
</div>
<div class="field">
  <label class="label">Batch Size</label>
  <div class="control">
    {{ form.batch_size }}
  </div>
  <p class="help">{{ form.batch_size.help_text }}</p>
  {{ form.batch_size.errors }}
</div>
<div class="field">
  <div id="export-file" class="file has-name">
    <label class="file-label">
      <input class="file-input" type="file" name="config_file" required_id="id_config_file">
      <span class="file-cta">
        <span class="file-icon">
          <i class="fa fa-upload"></i>
        </span>
        <span class="file-label">
          {% if form.instance.pk and form.instance.config_file.name %}
            Change Config File
          {% else %}
            Upload Config File
          {% endif %}
        </span>
      </span>
      <span class="file-name">
        {% if form.instance.pk and form.instance.config_file.name %}
        {{ form.instance.config_file.name }}
        {% else %}
          Choose a file...
        {% endif %}
      </span>
    </label>
  </div>
  {{ form.config_file.errors }}
</div>
<script>
  const fileInput = document.querySelector('#export-file input[type=file]');
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('#export-file .file-name');
      fileName.textContent = fileInput.files[0].name;
    }
  }
</script>
<div class="field">
  <label class="label">Extra Arguments</label>
  <div class="control">
    {{ form.extra_args }}
  </div>
  {{ form.extra_args.errors }}
</div>

templates/exports/partials/multi_export_details.html
{% load humanize %}
<section class="section app-card">
  <div class="level">
    <!-- Left side -->
    <div class="level-left">
      <h1 class="title">{{ export.name }} - Details</h1>
    </div>
    <div class="level-right">
      <a class="button is-danger is-rounded is-small is-outlined" href="{% url 'exports:delete_multi_export_config' export.id %}">
        <span class="icon">
          <i class="fa fa-times"></i>
        </span>
        <span>Delete</span>
      </a>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <span class="heading">Project Spaces</span>
      <h2>
        {% for project in export.projects.all %}
          <a href="{{ project.url }}" target="_blank" style="white-space: nowrap;">{{ project.domain }}
            <i class="fa fa-external-link"></i>
          </a>
          {% if not forloop.last %}<br>{% endif %}
        {% endfor %}
      </h2>
    </div>
    <div class="column">
      <span class="heading">Account</span>
      <h2>
        {{ export.account.username }}
      </h2>
    </div>
    <div class="column">
      <span class="heading">Database</span>
      <h2>
        {{ export.database.name }}
      </h2>
    </div>
    <div class="column">
      <span class="heading">Created By</span>
      <h2>
        {% if request.user == export.created_by %}You{% else %}{{ export.created_by.username}}{% endif %}
      </h2>
    </div>
    <div class="column">
      <span class="heading">Last Modified</span>
      <h2>
        {{ export.updated_at|naturaltime }}
      </h2>
    </div>
  </div>
  <div class="buttons">
  {% if show_back_button %}
    <a class="button is-primary is-rounded is-small" href="{% url 'exports:multi_export_details' export.id %}">
      <span class="icon">
        <i class="fa fa-arrow-left"></i>
      </span>
      <span>Back</span>
    </a>
  {% endif %}
    <a class="button is-primary is-rounded is-small is-outlined" href="{% url 'exports:download_multi_export_file' export.id %}">
      <span class="icon">
        <i class="fa fa-download"></i>
      </span>
      <span>Download Config File</span>
    </a>
    <a class="button is-primary is-rounded is-small is-outlined" href="{% url 'exports:edit_multi_export_config' export.id %}">
      <span class="icon">
        <i class="fa fa-edit"></i>
      </span>
      <span>Edit</span>
    </a>
  </div>
</section>

templates/exports/partials/multi_project_export_form.html
{% csrf_token %}
{{ form.non_field_errors }}
<div class="field">
  <label class="label">Name</label>
  <div class="control">
    {{ form.name }}
  </div>
  {{ form.name.errors }}
</div>
<div class="field">
  <label class="label">Projects</label>
  <div>
    {{ form.projects }}
  </div>
  {{ form.projects.errors }}
</div>
{% include 'exports/partials/export_form_shared.html' %}

templates/exports/partials/run_history.html
<section class="section app-card">
  <h1 class="title">Run History</h1>
  <div class="level">
    <div class="level-left">
      <button class="button is-primary is-rounded is-small" id="run-export-button">
        <span class="icon">
          <i class="fa fa-play"></i>
        </span>
        <span>Run Now</span>
      </button>
      <label class="checkbox mx-2 my-1">
        <input type="checkbox" id="force-sync-checkbox">
        Force sync of all data
      </label>
    </div>
    <div class="level-right">
      <label>Filter</label>
      {% if hide_skipped %}
        <a class="button is-primary is-rounded is-outlined is-small mx-2" href="?hide_skipped=n">
          <span>Show Queued and Skipped Items</span>
        </a>
      {% else %}
      <a class="button is-primary is-rounded is-outlined is-small mx-2" href="?hide_skipped=y">
        <span>Hide Queued and Skipped Items</span>
      </a>
      {% endif %}
    </div>
  </div>
  <div id="export-status-progress" class="progress-bar-demo my-2" style="display: none;">
    <div class='progress-wrapper'>
      <progress id="progress-bar" class="progress is-small is-primary" max="100"></progress>
    </div>
    <div id="progress-bar-message" style="color: grey;">Waiting for task to start...</div>
  </div>
{% include 'exports/partials/run_history_table.html' %}
</section>

templates/exports/partials/run_history_table.html
{% load dateformat_tags %}
{% load exports_tags %}
<table id="export-run-table" class="table is-fullwidth my-2">
  <thead>
  <tr>
    <th>Queued</th>
    <th>Started</th>
{% if is_partial_list  %}
    <th>Project</th>
{% endif  %}
    <th>Duration</th>
    <th>Status</th>
  {% if not is_multi_project %}
    <th>Log</th>
  {% endif %}
  {% if not is_partial_list %}
    <th>Config File</th>
  {% endif %}
  </tr>
  </thead>
  <tbody>
  {% for export_run in runs %}
    <tr>
      <td>
      <span class="icon" >
      {% if export_run.triggered_from_ui %}
        <i class="fa fa-user" title="Triggered from UI by {{ export_run.triggering_user|default:'unknown'}}"></i>
      {% elif export_run.triggered_from_ui == False %}
        <i class="fa fa-clock-o has-text-grey-light" title="Scheduled Run"></i>
      {% else %}
        <i class="fa fa-question has-text-grey-light" title="Unknown"></i>
      {% endif %}
      </span>

        {% if is_multi_project  %}<a href="{% url 'exports:multi_export_run_details' export.id export_run.id %}">{{ export_run.created_at }}</a>{% else %}{{ export_run.created_at }}{% endif %}
      </td>
      <td>{{ export_run.started_at|default:'-' }}</td>
      {% if is_partial_list  %}
        <td>{{ export_run.project.domain }}</td>
      {% endif  %}
      <td>{{ export_run.duration|readable_timedelta }}</td>
      <td>{{ export_run.status|to_status_icon }} {{ export_run.status }}</td>
      {% if not is_multi_project %}
      <td>
        <a class="log-trigger" data-open-status="closed" data-export-run-id="{{ export_run.id }}"><span class="icon"><i class="fa fa-chevron-down"></i></span>
          View log
        </a>
      </td>
      {% endif %}

      {% if not is_partial_list %}
      <td>
        {% if export_run.export_config_version.field_dict.config_file %}
        <a class="button is-primary is-rounded is-small is-outlined" href="{% url 'exports:download_export_file_version' export_run.export_config_version.id %}">
        <span class="icon">
          <i class="fa fa-download"></i>
        </span>
        </a>
        {% else %}
          <span class="has-text-grey">Not available</span>
        {% endif %}
      </td>
      {% endif %}

    </tr>
    {% if not is_multi_project %}
    <tr class="export-log my-1" id='export-log-{{ export_run.id }}' style="display: none;" >
      <td colspan="{% if is_multi_project  %}7{% else %}6{% endif %}">
        <pre class="wrapped">{{ export_run.log |default_if_none:"No logs yet…" }}</pre>
      </td>
    </tr>
    {% endif %}
  {% endfor %}
  </tbody>
</table>