apps/commcare/urls.py
from django.urls import path
from . import views


app_name = 'commcare'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'projects/create/', views.create_project, name='create_project'),
    path(r'projects/<int:project_id>/edit/', views.edit_project, name='edit_project'),
    path(r'accounts/create/', views.create_account, name='create_account'),
    path(r'accounts/<int:account_id>/edit/', views.edit_account, name='edit_account'),
]

apps/exports/urls.py
from django.urls import path
from . import views


app_name = 'exports'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'create/', views.create_export_config, name='create_export_config'),
    path(r'create/multi-project/', views.create_multi_export_config, name='create_multi_export_config'),
    path(r'view/<int:export_id>/', views.export_details, name='export_details'),
    path(r'view/<int:export_id>/edit/', views.edit_export_config, name='edit_export_config'),
    path(r'view/<int:export_id>/delete/', views.delete_export_config, name='delete_export_config'),
    path(r'download/<int:export_id>/config-file/', views.download_export_file, name='download_export_file'),
    path(r'download/version/<int:version_id>/config-file/', views.download_export_file_version,
         name='download_export_file_version'),
    path(r'view/multi-project/<int:export_id>/', views.multi_export_details, name='multi_export_details'),
    path(r'view/multi-project/<int:export_id>/run/<int:run_id>/', views.multi_export_run_details,
         name='multi_export_run_details'),
    path(r'view/multi-project/<int:export_id>/edit/', views.edit_multi_export_config,
         name='edit_multi_export_config'),
    path(r'view/multi-project/<int:export_id>/delete/', views.delete_multi_export_config,
         name='delete_multi_export_config'),
    path(r'download/multi-project/<int:export_id>/config-file/', views.download_multi_export_file,
         name='download_multi_export_file'),
    path(r'api/run/<int:export_id>/', views.run_export, name='run_export'),
    path(r'api/run/multi-project/<int:export_id>/', views.run_multi_export, name='run_multi_export'),
    path(r'databases/', views.databases, name='databases'),
    path(r'databases/create/', views.create_database, name='create_database'),
    path(r'databases/<int:database_id>/edit/', views.edit_database, name='edit_database'),
]

apps/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path(r'profile/', views.profile, name='user_profile'),
    path(r'profile/upload-image/', views.upload_profile_image, name='upload_profile_image'),
    path(r'avatars/<int:user_id>/', views.avatar, name='avatar'),
]

apps/web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.home, name='home'),
    path('admin-required', views.admin_required, name='admin_required'),
    path('terms', TemplateView.as_view(template_name="web/terms.html"), name='terms'),
]

commcare_sync/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view


schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('commcare/', include('apps.commcare.urls')),
    path('exports/', include('apps.exports.urls')),
    path('users/', include('apps.users.urls')),

    path('', include('apps.web.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
]

templates/web/components/app_nav.html
<aside class="menu">
  <p class="menu-label is-hidden-tablet-only">
    Export Management
  </p>
  <ul class="menu-list">
    <li>
      <a href="{% url 'exports:home' %}" {% if active_tab == 'exports' %}class="is-active"{% endif %}>
        <span class="icon"><i class="fa fa-home"></i></span><span class="is-hidden-tablet-only">Exports</span>
      </a>
    </li>
    <li>
      <a href="{% url 'exports:create_export_config' %}" {% if active_tab == 'create_export' %}class="is-active"{% endif %}>
        <span class="icon"><i class="fa fa-plus"></i></span><span class="is-hidden-tablet-only">New Export</span>
      </a>
    </li>
    <li>
      <a href="{% url 'exports:create_multi_export_config' %}" {% if active_tab == 'create_multi_export' %}class="is-active"{% endif %}>
        <span class="icon"><i class="fa fa-plus"></i></span><span class="is-hidden-tablet-only">Multi-Project Export</span>
      </a>
    </li>
    <li>
      <a href="{% url 'exports:databases' %}" {% if active_tab == 'databases' %}class="is-active"{% endif %}>
        <span class="icon"><i class="fa fa-database"></i></span><span class="is-hidden-tablet-only">Databases</span>
      </a>
    </li>
  </ul>
  <p class="menu-label is-hidden-tablet-only">
    CommCare Management
  </p>
  <ul class="menu-list">
    <li>
      <a href="{% url 'commcare:home' %}" {% if active_tab == 'commcare' %}class="is-active"{% endif %}>
        <span class="icon"><i class="fcc fcc-flower"></i></span><span class="is-hidden-tablet-only">CommCare Setup</span>
      </a>
    </li>
    <li>
      <a href="{% url 'commcare:create_project' %}" {% if active_tab == 'create_project' %}class="is-active"{% endif %}>
        <span class="icon"><i class="fa fa-plus"></i></span><span class="is-hidden-tablet-only">Add Project</span>
      </a>
    </li>
    <li>
      <a href="{% url 'commcare:create_account' %}" {% if active_tab == 'create_account' %}class="is-active"{% endif %}>
        <span class="icon"><i class="fa fa-user-plus"></i></span><span class="is-hidden-tablet-only">Add Account</span>
      </a>
    </li>
  </ul>
  <p class="menu-label is-hidden-tablet-only">
    My Account
  </p>
  <ul class="menu-list">
    <li>
        <a href="{% url 'users:user_profile' %}" {% if active_tab == 'profile' %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-user"></i></span><span class="is-hidden-tablet-only">Profile</span>
        </a>
    </li>
    <li>
        <a href="{% url 'account_change_password' %}" {% if 'accounts/password/change' in request.path %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-unlock-alt"></i></span><span class="is-hidden-tablet-only">Change Password</span>
        </a>
    </li>
    <li>
        <a href="{% url 'account_logout' %}" {% if 'accounts/logout' in request.path %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-sign-out"></i></span><span class="is-hidden-tablet-only">Sign out</span>
        </a>
    </li>
  </ul>
</aside>

templates/web/components/favicon.html
{# see https://realfavicongenerator.net #}
<link rel="apple-touch-icon" sizes="180x180" href="/static/images/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicons/favicon-16x16.png">
<link rel="manifest" href="/static/images/favicons/site.webmanifest">
<link rel="mask-icon" href="/static/images/favicons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/static/images/favicons/favicon.ico">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="msapplication-config" content="/static/images/favicons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

templates/web/components/footer.html
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      {{project_meta.NAME}} &mdash; Copyright <span id="copyright-year">2019</span>
    </p>
  </div>
</footer>
<script>
    document.getElementById('copyright-year').innerText = (new Date()).getFullYear();
</script>

templates/web/components/google_analytics.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS_ID  }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ GOOGLE_ANALYTICS_ID  }}');
</script>

templates/web/components/messages-js.html
<script type="application/javascript">
    document.addEventListener('DOMContentLoaded', () => {
      (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
        let $notification = $delete.parentNode;
        $delete.addEventListener('click', () => {
          $notification.parentNode.removeChild($notification);
        });
      });
    });
</script>

templates/web/components/messages.html
{% if messages %}
    {% for message in messages %}
    <section class="app-message notification {% if message.tags %}is-{% if message.level_tag == 'error' %}danger{% else %}{{ message.level_tag }}{% endif %}{% endif %} {{ message.extra_tags }}" >
        <button class="delete"></button>
        {{ message }}
    </section>
    {% endfor %}
{% endif %}

templates/web/components/meta.html
{% load meta_tags %}
{% load static %}
{% if project_meta %}
{% with project_meta|get_title:page_title as title %}
{% with project_meta|get_description:page_description as description %}
{% with project_meta|get_image_url:page_image as image %}
    <title>{{ title }}</title>
    <meta name="description" content="{{ description }}">
    <meta name="keywords" content="{{ project_meta.KEYWORDS }}">
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="{{ title }}">
    <meta name="twitter:description" content="{{ description }}">
    <meta name="twitter:image" content="{{ image }}">
    <!-- Open Graph data -->
    <meta property="og:title" content="{{ title }}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="{{ page_url }}" />
    <meta property="og:image" content="{{ image }}" />
    <meta property="og:description" content="{{ description }}" />
    <meta property="og:site_name" content="{{ project_meta.NAME }}" />
    <link rel="canonical" href="{% if page_canonical_url %}{{ page_canonical_url }}{% else %}{{ page_url }}{% endif %}">
{% endwith %}
{% endwith %}
{% endwith %}
{% endif %}

templates/web/components/navbar-js.html
<script type="application/javascript">
    // see: https://bulma.io/documentation/components/navbar/
    document.addEventListener('DOMContentLoaded', () => {
        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {
            // Add a click event on each of them
            $navbarBurgers.forEach(el => {
                el.addEventListener('click', () => {
                    // Get the target from the "data-target" attribute
                    const target = el.dataset.target;
                    const $target = document.getElementById(target);

                    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                    el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');
                });
            });
        }
    });
</script>

templates/web/components/team_nav.html
{% load team_tags %}
{% if request.team and request.user|is_admin_of:request.team %}
  <li>
      <a href="{% url 'web:team_admin' request.team.slug %}" {% if active_tab == 'team-admin' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-gear"></i></span><span class="is-hidden-tablet-only">Admin</span>
      </a>
  </li>



{% endif %}

templates/web/components/top_nav.html
{% load static %}
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'web:home' %}">
          <img src="{% static 'images/commcare-flower.png' %}" width="28" height="28">
          <span class="mx-2">{{project_meta.NAME}}</span>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="nav-menu">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" id="nav-menu">
        <div class="navbar-end">
          {% if user.is_authenticated %}
            {% if user.is_superuser and user.is_staff %}
              <a class="navbar-item" href="{% url 'admin:index' %}">
                Admin Site
              </a>
            {% endif %}
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <img class="avatar is-hidden-touch" src="{{ user.avatar_url}}">
                <span class="is-hidden-desktop">My Account</span>
              </a>
              <div class="navbar-dropdown is-right">
                <a class="navbar-item" href="{% url 'users:user_profile' %}" >
                  <span class="icon"><i class="fa fa-user"></i></span><span>Profile</span>
                </a>
                <a class="navbar-item" href="{% url 'account_change_password' %}">
                  <span class="icon"><i class="fa fa-unlock-alt"></i></span><span>Change Password</span>
                </a>
                <a class="navbar-item" href="{% url 'account_logout' %}" >
                  <span class="icon"><i class="fa fa-sign-out"></i></span><span>Sign out</span>
                </a>
              </div>
            </div>
          {% else %}
              <div class="navbar-item">
                  <div class="buttons">
                      <a class="button is-primary is-outlined" href="{% url 'account_signup' %}">Sign up</a>
                      <a class="button is-text" href="{% url 'account_login' %}">Sign in</a>
                  </div>
              </div>
          {% endif %}
        </div>
      </div>
    </div>
</nav>