apps/commcare/urls.py
from django.urls import path
from . import views


app_name = 'commcare'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'projects/create/', views.create_project, name='create_project'),
    path(r'projects/<int:project_id>/edit/', views.edit_project, name='edit_project'),
    path(r'accounts/create/', views.create_account, name='create_account'),
    path(r'accounts/<int:account_id>/edit/', views.edit_account, name='edit_account'),
]

commcare_sync/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view


schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('commcare/', include('apps.commcare.urls')),
    path('exports/', include('apps.exports.urls')),
    path('users/', include('apps.users.urls')),

    path('', include('apps.web.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
]

apps/commcare/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _


class BaseModel(models.Model):
    """
    Base model that includes default created / updated timestamps.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class CommCareServer(BaseModel):
    name = models.CharField(max_length=100, default='CommCare HQ')
    url = models.CharField(
        max_length=100, default=settings.COMMCARE_DEFAULT_SERVER,
        unique=True,
    )

    def __str__(self):
        return f'{self.name} ({self.url})'

    def get_url_base(self):
        """
        Returns the url with no trailing slash.
        """
        return self.url.rstrip('/')


class CommCareProject(BaseModel):
    server = models.ForeignKey(CommCareServer, on_delete=models.CASCADE)
    domain = models.CharField(
        max_length=100,
        help_text=_("Your CommCare domain (available from the URL)")
    )

    class Meta:
        unique_together = ('server', 'domain')

    def __str__(self):
        return f'{self.domain} ({self.server.name})'

    @property
    def url(self):
        return f'{self.server.get_url_base()}/a/{self.domain}/'


class CommCareAccount(BaseModel):
    server = models.ForeignKey(CommCareServer, on_delete=models.CASCADE)
    username = models.EmailField(
        max_length=100,
        help_text=_("The email address you use to sign into CommCare HQ")
    )
    api_key = models.CharField(
        max_length=40,
        help_text=_('Your API key is available under "My Account Settings" in CommCare.')
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('server', 'username')

    def __str__(self):
        return self.username

apps/commcare/forms.py
from django import forms
from .models import CommCareProject, CommCareAccount


class CommCareProjectForm(forms.ModelForm):

    class Meta:
        model = CommCareProject
        fields = ('server', 'domain')


class CommCareAccountForm(forms.ModelForm):
    api_key = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CommCareAccount
        fields = ('server', 'username', 'api_key')

apps/commcare/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from .forms import CommCareProjectForm, CommCareAccountForm
from .models import CommCareProject, CommCareAccount


@login_required
def home(request):
    projects = CommCareProject.objects.order_by('domain')
    accounts = CommCareAccount.objects.order_by('username')
    return render(request, 'commcare/commcare_home.html', {
        'active_tab': 'commcare',
        'projects': projects,
        'accounts': accounts,
    })


@login_required
def create_project(request):
    if request.method == 'POST':
        form = CommCareProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save()
            messages.success(request, f'Project {project.domain} was successfully added.')
            return HttpResponseRedirect(reverse('commcare:home'))
    else:
        form = CommCareProjectForm()

    return render(request, 'commcare/create_project.html', {
        'active_tab': 'create_project',
        'form': form,
    })


@login_required
def edit_project(request, project_id):
    project = get_object_or_404(CommCareProject, id=project_id)
    if request.method == 'POST':
        form = CommCareProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            project = form.save()
            messages.success(request, f'Project {project} was successfully saved.')
            return HttpResponseRedirect(reverse('commcare:home'))
    else:
        form = CommCareProjectForm(instance=project)

    return render(request, 'commcare/edit_project.html', {
        'active_tab': 'commcare',
        'form': form,
        'project': project,
    })


@login_required
def create_account(request):
    if request.method == 'POST':
        form = CommCareAccountForm(request.POST, request.FILES)
        if form.is_valid():
            account = form.save(commit=False)
            account.owner = request.user
            account.save()
            messages.success(request, f'Account {account.username} was successfully added.')
            return HttpResponseRedirect(reverse('commcare:home'))
    else:
        form = CommCareAccountForm()

    return render(request, 'commcare/create_account.html', {
        'active_tab': 'create_account',
        'form': form,
    })


@login_required
def edit_account(request, account_id):
    account = get_object_or_404(CommCareAccount, id=account_id)
    if not request.user == account.owner:
        messages.warning(request, _("Sorry, you don't have permission to edit that account"))
        return HttpResponseRedirect(reverse('commcare:home'))
    if request.method == 'POST':
        form = CommCareAccountForm(request.POST, request.FILES, instance=account)
        if form.is_valid():
            account = form.save()
            messages.success(request, _('Account {account} was successfully saved.').format(account=account))
            return HttpResponseRedirect(reverse('commcare:home'))
    else:
        form = CommCareAccountForm(instance=account)

    return render(request, 'commcare/edit_account.html', {
        'active_tab': 'commcare',
        'form': form,
        'account': account,
    })

templates/commcare/commcare_home.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">CommCare Home</h1>
  <h2 class="subtitle">View and manage your CommCare connections</h2>
</section>
<section class="section app-card">
  <h1 class="title">Projects</h1>
  <h2 class="subtitle">Manage the CommCare project spaces you'll connect to here</h2>
{% if projects.exists %}
  <a class="button is-primary is-rounded is-small is-outlined" href="{% url 'commcare:create_project' %}">
    <span class="icon">
      <i class="fa fa-plus"></i>
    </span>
    <span>Add Project</span>
  </a>
  <table class="table is-striped is-fullwidth">
    <thead>
    <tr>
      <th>Project</th>
      <th>View</th>
      <th>Edit</th>
    </tr>
    </thead>
    <tbody>
    {% for project in projects %}
      <tr>
        <td>{{ project.domain }}</td>
        <td><a href="{{ project.url }}" target="_blank">View in CommCare <i class="fa fa-external-link"></i></a></td>
        <td>
          <a class="button is-small is-primary is-rounded is-outlined" href="{% url 'commcare:edit_project' project.id %}">
            <span class="icon">
              <i class="fa fa-edit"></i>
            </span>
            <span>Edit</span>
          </a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <section class="notification is-warning is-light">
    No projects found!
  </section>
  <a class="button is-primary " href="{% url 'commcare:create_project' %}">
    <span class="icon">
      <i class="fa fa-plus"></i>
    </span>
    <span>Add Your First Project</span>
  </a>
{% endif %}
</section>
<section class="section app-card">
  <h1 class="title">Accounts</h1>
  <h2 class="subtitle">Manage the CommCare accounts used to sync your data</h2>
{% if accounts.exists %}
  <a class="button is-primary is-rounded is-small is-outlined" href="{% url 'commcare:create_account' %}">
    <span class="icon">
      <i class="fa fa-plus"></i>
    </span>
    <span>Add Account</span>
  </a>
  <table class="table is-striped is-fullwidth">
    <thead>
    <tr>
      <th>Username</th>
      <th>Created</th>
      <th>Owner</th>
      <th>Edit</th>
    </tr>
    </thead>
    <tbody>
    {% for account in accounts %}
      <tr>
        <td>{{ account.username }}</td>
        <td>{{ account.created_at }}</td>
        <td>{% if request.user == account.owner %}You{% else %}{{ account.owner.get_display_name }}{% endif %}</td>
        <td>
          {% if request.user == account.owner %}
          <a class="button is-small is-primary is-rounded is-outlined" href="{% url 'commcare:edit_account' account.id %}">
            <span class="icon">
              <i class="fa fa-edit"></i>
            </span>
            <span>Edit</span>
          </a>
          {% else %}
            &mdash;
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <section class="notification is-warning is-light">
    No accounts found!
  </section>
  <a class="button is-primary " href="{% url 'commcare:create_account' %}">
    <span class="icon">
      <i class="fa fa-plus"></i>
    </span>
    <span>Add Your First Account</span>
  </a>
{% endif %}
</section>
{% endblock app %}

templates/commcare/create_account.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Add Account</h1>
  <form method="post" enctype="multipart/form-data">
    {% include 'commcare/partials/account_form.html' %}
    <div class="field is-grouped">
        <div class="control">
            <input class="button is-primary" type="submit" value="Add Account">
        </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/commcare/create_project.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Add Project</h1>
  <form method="post" enctype="multipart/form-data">
    {% include 'commcare/partials/project_form.html' %}
    <div class="field is-grouped">
        <div class="control">
            <input class="button is-primary" type="submit" value="Add Project">
        </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/commcare/edit_account.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Edit Account</h1>
  <form method="post" enctype="multipart/form-data">
    {% include 'commcare/partials/account_form.html' %}
    <div class="field is-grouped">
        <div class="control">
            <input class="button is-primary" type="submit" value="Save Account">
        </div>
    </div>
  </form>
</section>
{% endblock app %}

templates/commcare/edit_project.html
{% extends "web/app/app_base.html" %}
{% block app %}
<section class="section app-card">
  <h1 class="title">Edit {{ project.domain }}</h1>
  <form method="post" enctype="multipart/form-data">
    {% include 'commcare/partials/project_form.html' %}
    <div class="field is-grouped">
        <div class="control">
            <input class="button is-primary" type="submit" value="Save">
        </div>
    </div>
  </form>
</section>
{% endblock app %}